### ISSUE TITLE
pipr not building anymore

### ISSUE THREAD

**Issue by devhell** [elkowar/pipr#6]
Hi,

I'm not the maintainer for your package on NixOS, but I've noticed that recent builds of `pipr` are failing. Please see the build [log](https://headcounter.org/hydra/build/3244505/nixlog/11) for more details. There seem to have been some changes in Rust lately, which also affected a number of other Rust apps like, for example, [pastel](https://github.com/sharkdp/pastel).

Thank you very much also for such an awesome and useful tool! Prost! :beers:

PS: I'm a dumbass, I just noticed that you are the NixOS maintainer yourself. :rofl: Sorry!

**Comment by legendofmiracles** [comment]
Will be fixed with https://github.com/NixOS/nixpkgs/pull/144884

**Comment by devhell** [comment]
Fantastic, thank you @legendofmiracles ! :beers:
